### ISSUE TITLE
display-pixel-* from emacs is a lie?

### ISSUE THREAD

**Issue by zenspider** [mnp/dispwatch#4]
I've seen this on 2 macbooks & an HP monitor... the values that come back from `display-pixel-*` (which uses `x-display-pixel-*`) seems to be a lie. Specifically, switching from one resolution to another seems to generate a myriad of values... I'm trying to get my lookup table working for OSX's 5 scaling factors, but I've gone through 7-8 by now by going up and down. I've seen similar screwups when I change font size and then ask for `frame-width`... it often takes a while for the values to change or they're just inconsistent.

What IS consistent is the geometry values that you're using to detect changes. When you call `display-monitor-attributes-list` it calls a different C function based on os (`ns-display-monitor-attributes` in my case) and that seems to be more consistent.

Here's what I'm currently using as my hook:

```elisp
(defun rwd/display-change (_disp)       ; ignore this incoming var
  (interactive)
  (when window-system
    (let* ((attr (frame-monitor-attributes))
           (geom (assoc 'geometry attr))
           (w (nth 3 geom))
           (h (nth 4 geom))
           (disp (format "%sx%s" w h))  ; calculated from actual geometry
           (args (assoc disp rwd/displays))
           (default (assoc "default" rwd/displays)))
      (message "rwd/display-change %s" disp)
      (unless args
        (find-variable 'rwd/displays)
        (insert (format "%S\n" (list disp 'w 'h "Font" 16)))
        (message "Please extend rwd/displays with %S" disp)
        (setq args default))
      (apply 'rwd/display-setup (cdr args))
      (rwd-fix-fullscreen)
      (sleep-for 0.25)
      (rwd-split-smart))))
```

I'm good for now, but you might want to consider having a `geometry-change` hook. Happy to send a patch if you want.

**Comment by mnp** [comment]
Sure, if you have have one, PR it. Thanks!

**Comment by zenspider** [comment]
Took me long enough... 

```elisp
(defvar dispwatch-geom-changed-hooks '())

(defun rwd/dispwatch-handler (disp)
  (let* ((args    (assoc disp      rwd/displays))
         (default (assoc "default" rwd/displays)))
    (unless args
      (find-variable 'rwd/displays)
      (insert (format "%S\n" (list disp 'w 'h 16)))
      (message "Please extend rwd/displays with %S" disp)
      (setq args default))
    (apply 'rwd/display-setup (cdr args))
    (rwd-split-smart)))

(add-hook 'dispwatch-geom-changed-hooks 'rwd/dispwatch-handler)

;; TODO: push upstream
(defun rwd/dispwatch-display-change-hook (_disp)
  (let* ((attr (frame-monitor-attributes))
         (geom (assoc 'geometry attr))
         (w (nth 3 geom))
         (h (nth 4 geom))
         (disp (format "%sx%s" w h))) ; calculated from actual geometry
    (run-hook-with-args 'dispwatch-geom-changed-hooks disp)))
```

if that feels good to you, I can submit a PR.

ETA: `rwd/dispwatch-handler` is just to illustrate.

**Comment by mnp** [comment]
Sure, go ahead and PR it, then I can try to test on a few different platforms and see if I can reproduce your success.

Thanks!

**Comment by zenspider** [comment]
Poke.
